# SEGUNDA AVALIAÇÃO DE ECONOMETRIA

## Importação das Bibliotecas

In [1]:
# Análise de dados básica

import pandas as pd
import numpy as np

# Visualização

import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import Axes3D
import seaborn as sns

# Econometria

import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.stats.diagnostic import het_breuschpagan
from linearmodels.iv import IV2SLS
from statsmodels.stats.stattools import durbin_watson 
from linearmodels.panel import PanelOLS
import linearmodels.panel as pl
from linearmodels import PanelOLS, RandomEffects
from linearmodels.panel import compare, PooledOLS
import statsmodels.api as sm

# Estatística

from scipy import stats

## Configuração do Display

In [2]:
# O pandas foi configurado para mostrar todas as colunas e as 100 primeiras linhas

pd.set_option('display.max_columns', None)  
pd.set_option('display.max_rows', 10)

## Carregamento da Base de Dados

In [3]:
# O caminho do arquivo (base de dados) foi guardado em uma variável

caminho_arquivo = "/home/ph-padrim/Área de trabalho/Trabalho de Econometria/trabalho 2/painel_2011-2021_raisfirmasmg.csv"

# O arquivo CSV foi transformado em um dataframe

df = pd.read_csv(caminho_arquivo, encoding='UTF-8')  

# Criando a coluna com o quadrado da idade_med

df['idade_med_quadrado'] = df['idade_med'] ** 2

# Criando interação entre sexo e raça/cor. Se forem categóricas, primeiro crie dummies

df['sexo_raca_interacao'] = df['sexo_med'] * df['raca_cor_med']

# Criando dummies de nível técnico da firma

dummies = pd.get_dummies(df['nivel_tec'], prefix='nivel_tec')
dummies = dummies[[f'nivel_tec_{i}' for i in range(1, 6)]]  # Remove o nível 0
df = pd.concat([df, dummies], axis=1)

# Convertendo as dummies em inteiros

for nivel in range(1, 6):
    df[f'nivel_tec_{nivel}'] = (df['nivel_tec'] == nivel).astype(int)

# Cria variáveis dummy para cada ano no período 2011-2021. Exemplo: d_2011 = 1 se o ano é 2011, 0 caso contrário

years = range(2011, 2021+1)
for ano in years:
    df[f'd_{ano}'] = np.where(df['ano'] == ano, 1, 0)

# Dropando os anos que não possuem observação: 2012, 2014, 2016, 2018, 2020

df = df.drop(['d_2012', 'd_2014', 'd_2016', 'd_2018', 'd_2020'], axis=1)

df_index = df.set_index(['firma', 'ano'])
display(df_index)

# Contando quantos valores zerados da variável df['remun_med_real_med'] e excluindo 
print('Informações importantes:')
print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')
quantidade_zeros = (df['remun_med_real_med'] == 0).sum()
print(f'1) Existem {quantidade_zeros} valores 0 da variável remun_med_real_med na base original da RAIS. Serão excluídos, pois são poucos (representam {(quantidade_zeros/393606)*100:.4}%) do total.')
df = df[df['remun_med_real_med'] != 0] 

# Contando quantos valores possuem 'NA' e excluindo 

print(f"2) Foram excluídas {390780 - 311862} linhas ({(78918/393606*100):.4}% do total) que possuíam algum NA nas variáveis utilizadas em algum momento da modelagem. Portanto, o painel será desbalanceado.")
print('--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------')

# Logaritmizando o y e adicionando na base df

y_log = np.log(df['remun_med_real_med']) 
df['y_log'] = y_log

# Nome da coluna que você quer classificar
coluna_nivel_tecnologico = 'nivel_tec'

# Nome da nova coluna que será criada
nova_coluna_classificacao = 'nivel_tec_classificado'

# Verifica se a coluna 'nivel_tec' existe antes de tentar classificá-la
if coluna_nivel_tecnologico in df.columns:
    # Classifica a firma: 1 se 'nivel_tec' for 5, 0 caso contrário
    # Esta é a forma mais concisa e eficiente em Pandas
    df[nova_coluna_classificacao] = (df[coluna_nivel_tecnologico] == 5).astype(int)

    # Alternativa usando .apply (um pouco menos performática para grandes DFs, mas mais explícita na lógica)
    # df[nova_coluna_classificacao] = df[coluna_nivel_tecnologico].apply(lambda x: 1 if x == 5 else 0)

    print("\nDataFrame com a nova coluna de classificação (Diretamente no 'df'):")
    print(df)
    print("-" * 50)
else:
    print(f"Erro: A coluna '{coluna_nivel_tecnologico}' não foi encontrada no DataFrame.")

# Você pode salvar o DataFrame modificado se desejar
# df.to_csv('rais_modificada.csv', index=False)
# df.to_excel('rais_modificada.xlsx', index=False)

# Nome da coluna de ano
coluna_ano = 'ano'

# Nome da nova coluna que será criada
nova_coluna_classificacao_ano = 'ano_classificado'

# Verifica se a coluna 'ano' existe antes de tentar classificá-la
if coluna_ano in df.columns:
    # Classifica o ano: 1 se 'ano' for 2021, 0 caso contrário
    # Usa a comparação booleana e converte True/False para 1/0
    df[nova_coluna_classificacao_ano] = (df[coluna_ano] == 2021).astype(int)

    print("\nDataFrame com a nova coluna 'ano_classificado':")
    print(df)
    print("-" * 50)
else:
    print(f"Erro: A coluna '{coluna_ano}' não foi encontrada no DataFrame.")

# Criando interação entre dummy de nivel_tec e ano. Se forem categóricas, primeiro crie dummies

df['tec_ano_interacao'] = df['nivel_tec_classificado'] * df['ano_classificado']

# Define as variáveis explicativas

controle_vars = ["idade_med", "idade_med_quadrado", "sexo_med", "raca_cor_med", "superior_med", "sexo_raca_interacao", "nivel_tec_1", "nivel_tec_2", "nivel_tec_3", "nivel_tec_4", "nivel_tec_5"]

# Calcula médias por indivíduo (firma) para todas as variáveis. Isso é necessário para a abordagem de Mundlak

years2 = range(2011, 2021+1, 2)
for var in controle_vars + [f'd_{ano}' for ano in years2]:
    df[f'mean_{var}'] = df.groupby('firma')[var].transform('mean')

# Configura o índice do painel principal (df) usando a identificação da firma e o ano

df_index = df.set_index(['firma', 'ano'])

# Configura o índice do painel secundário (dados usados em algum momento na modelagem) usando a identificação da firma e o ano

dados_limpos = df[['firma', 'ano', 'y_log', 'adultos_med', 'idade_med', 'superior_med', 'idade_med_quadrado', 'sexo_med', 'raca_cor_med', 'sexo_raca_interacao', 'nivel_tec_1', 'nivel_tec_2', 'nivel_tec_3', 'nivel_tec_4', 'nivel_tec_5', 'ano_classificado', 'nivel_tec_classificado', 'tec_ano_interacao', 'remun_med_real_med']].dropna()
dados_limpos_index = dados_limpos.set_index(['firma', 'ano'])

            sexo_med  raca_cor_med  tempo_emprego_med  idade_med  \
firma ano
1     2011  0.000000      1.000000           9.450000  25.500000
      2021  1.000000      0.500000          53.300000  26.000000
      2015  0.250000      0.750000          10.925000  22.250000
      2019  0.400000      0.600000          40.939999  25.799999
      2013  1.000000      0.000000           6.900000  23.000000
...              ...           ...                ...        ...
65601 2017  0.070746      0.183556          90.150864  36.430210
      2019  0.078431      0.252941          94.140785  37.501961
      2015  0.077535      0.210736          82.044731  35.035786
      2021  0.126957           NaN          85.735652  37.086957
      2013  0.072016      0.240741          74.588066  34.633743

            remun_med_real_med    hb_med    hn_med    mb_med    mn_med  \
firma ano
1     2011          909.060543  0.000000  1.000000  0.000000  0.000000
      2021         1651.425000  0.000000  0.000000  0.500000  0.500000
      2015         1467.106445  0.000000  0.750000  0.250000  0.000000
      2019         1251.502930  0.000000  0.600000  0.400000  0.000000
      2013         1973.719360  0.000000  0.000000  1.000000  0.000000
...                        ...       ...       ...       ...       ...
65601 2017         4256.148438  0.751434  0.177820  0.065010  0.005736
      2019         3932.223633  0.690196  0.231373  0.056863  0.021569
      2015         4376.018555  0.719682  0.202783  0.069583  0.007952
      2021         3385.715687       NaN       NaN       NaN       NaN
      2013         4785.799316  0.699588  0.228395  0.059671  0.012346

            envelhecidos_med  adultos_med  jovens_med  ate_fundamental_med  \
firma ano
1     2011          0.000000     0.000000    1.000000             0.500000
      2021          0.000000     0.000000    1.000000             0.000000
      2015          0.000000     0.000000    1.000000             0.750000
      2019          0.000000     0.200000    0.800000             0.200000
      2013          0.000000     0.000000    1.000000             0.000000
...                      ...          ...         ...                  ...
65601 2017          0.036329     0.512428    0.451243             0.152964
      2019          0.050980     0.554902    0.394118             0.131373
      2015          0.037773     0.425447    0.536779             0.174950
      2021          0.057391     0.540870    0.401739             0.120000
      2013          0.034979     0.390947    0.574074             0.185185

            superior_med  rotatividade_med  mismatchover_med  \
firma ano
1     2011      0.000000          0.000000          0.500000
      2021      0.000000          0.000000          0.000000
      2015      0.000000          0.000000          0.750000
      2019      0.000000          0.000000          0.200000
      2013      0.000000          0.000000          0.000000
...                  ...               ...               ...
65601 2017      0.135755          0.009560          0.172084
      2019      0.209804          0.011765          0.147059
      2015      0.161034          0.009940          0.182903
      2021      0.215652          0.017391          0.135652
      2013      0.176955          0.022634          0.156379

            mismatchunder_med  mismatchnull_med  tempo_emprego_a1_med  \
firma ano
1     2011           0.000000          0.500000              0.500000
      2021           0.000000          1.000000              0.500000
      2015           0.000000          0.250000              0.750000
      2019           0.000000          0.800000              0.200000
      2013           0.000000          1.000000              1.000000
...                       ...               ...                   ...
65601 2017           0.156788          0.671128              0.080306
      2019           0.135294          0.717647              0.131373
      2015           0.192843          0.624254              0.147117
      2021           0.151304          0.713043              0.224348
      2013           0.286008          0.557613              0.154321

            tempo_emprego_2a5_med  tempo_emprego_6mais_med  sal_hora_med  \
firma ano
1     2011               0.500000                 0.000000      5.165117
      2021               0.000000                 0.500000      9.383097
      2015               0.250000                 0.000000      8.335832
      2019               0.600000                 0.200000      7.744656
      2013               0.000000                 0.000000     11.214314
...                           ...                      ...           ...
65601 2017               0.391969                 0.527725     24.471148
      2019               0.333333                 0.535294     22.640743
      2015               0.343936                 0.508946     25.156115
      2021               0.300870                 0.474783           NaN
      2013               0.419753                 0.425926     27.420103

            cbo_h1_med cbo_h2_med  cbo_h3_med  sal_hora_dp  produtividade  \
firma ano
1     2011    0.000000          0    1.000000     0.379776      20.660467
      2021    0.500000        NaN    0.500000     4.946493      37.532386
      2015    0.000000        NaN    0.750000     2.793418      33.343327
      2019    0.000000        NaN    0.800000     2.955299      31.603609
      2013    0.000000        NaN    0.000000          NaN      44.857258
...                ...        ...         ...          ...            ...
65601 2017    0.001912        NaN    0.986616    16.885422      97.999718
      2019    0.005882        NaN    0.988235    15.209931      91.214142
      2015    0.003976        NaN    0.978131    18.036247     100.895554
      2021         NaN        NaN         NaN          NaN      79.819046
      2013    0.004115        NaN    0.985597    19.770716     109.805420

            data_abertura  data_encerramento  municipio  natureza_juridica  \
firma ano
1     2011       20052008                  0     313930               2135
      2021       20052008                  0     313930               2135
      2015       20052008                  0     313930               2135
      2019       20052008                  0     313930               2135
      2013       20052008                  0     313930               2135
...                   ...                ...        ...                ...
65601 2017        2032005                  0     317010               2046
      2019        2032005                  0     317010               2046
      2015        2032005                  0     317010               2046
      2021        2032005                  0     317010               2046
      2013        2032005                  0     317010               2046

            qtd_vinc_atv  ibge_subset  ind_atv_ano  cnae_20  nivel_tec  \
firma ano
1     2011             1           16            1       45          1
      2021             2           16            1       45          2
      2015             4           16            1       45          1
      2019             4           16            1       45          2
      2013             1           16            1       45          0
...                  ...          ...          ...      ...        ...
65601 2017           454            7            1       16          4
      2019           443            7            1       16          2
      2015           451            7            1       16          1
      2021           470            7            1       16          1
      2013           437            7            1       16          1

            tamanho  idade  tamanho_2  setor_2  regiao  idade_med_quadrado  \
firma ano
1     2011        1    4.0        1.0      3.0     3.0          650.250000
      2021        2    NaN        1.0      3.0     3.0          676.000000
      2015        2    NaN        NaN      NaN     NaN          495.062500
      2019        2    NaN        NaN      NaN     NaN          665.639961
      2013        1    NaN        NaN      NaN     NaN          529.000000
...             ...    ...        ...      ...     ...                 ...
65601 2017        5    NaN        NaN      NaN     NaN         1327.160209
      2019        5    NaN        NaN      NaN     NaN         1406.397060
      2015        5    NaN        NaN      NaN     NaN         1227.506278
      2021        5    NaN        5.0      1.0     3.0         1375.442344
      2013        5    NaN        NaN      NaN     NaN         1199.496174

            sexo_raca_interacao  nivel_tec_1  nivel_tec_2  nivel_tec_3  \
firma ano
1     2011             0.000000            1            0            0
      2021             0.500000            0            1            0
      2015             0.187500            1            0            0
      2019             0.240000            0            1            0
      2013             0.000000            0            0            0
...                         ...          ...          ...          ...
65601 2017             0.012986            0            0            0
      2019             0.019839            0            1            0
      2015             0.016339            1            0            0
      2021                  NaN            1            0            0
      2013             0.017337            1            0            0

            nivel_tec_4  nivel_tec_5  d_2011  d_2013  d_2015  d_2017  d_2019  \
firma ano
1     2011            0            0       1       0       0       0       0
      2021            0            0       0       0       0       0       0
      2015            0            0       0       0       1       0       0
      2019            0            0       0       0       0       0       1
      2013            0            0       0       1       0       0       0
...                 ...          ...     ...     ...     ...     ...     ...
65601 2017            1            0       0       0       0       1       0
      2019            0            0       0       0       0       0       1
      2015            0            0       0       0       1       0       0
      2021            0            0       0       0       0       0       0
      2013            0            0       0       1       0       0       0

            d_2021
firma ano
1     2011       0
      2021       1
      2015       0
      2019       0
      2013       0
...            ...
65601 2017       0
      2019       0
      2015       0
      2021       1
      2013       0

[393606 rows x 54 columns]

Informações importantes:
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1) Existem 2826 valores 0 da variável remun_med_real_med na base original da RAIS. Serão excluídos, pois são poucos (representam 0.718%) do total.
2) Foram excluídas 78918 linhas (20.05% do total) que possuíam algum NA nas variáveis utilizadas em algum momento da modelagem. Portanto, o painel será desbalanceado.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

DataFrame com a nova coluna de classificação (Diretamente no 'df'):
        sexo_med  raca_cor_med  tempo_emprego_med  idade_med  \
0       0.000000      1.000000           9.450000  25.500000
1       1.000000      0.500000          53.300000  26.000000
2       0.250000      0.750000          10.925000  22.250000
3       0.400000      0.600000          40.939999  25.799999
4       1.000000      0.000000           6.900000  23.000000
...          ...           ...                ...        ...
393601  0.070746      0.183556          90.150864  36.430210
393602  0.078431      0.252941          94.140785  37.501961
393603  0.077535      0.210736          82.044731  35.035786
393604  0.126957           NaN          85.735652  37.086957
393605  0.072016      0.240741          74.588066  34.633743

        remun_med_real_med    hb_med    hn_med    mb_med    mn_med  \
0               909.060543  0.000000  1.000000  0.000000  0.000000
1              1651.425000  0.000000  0.000000  0.500000  0.500000
2              1467.106445  0.000000  0.750000  0.250000  0.000000
3              1251.502930  0.000000  0.600000  0.400000  0.000000
4              1973.719360  0.000000  0.000000  1.000000  0.000000
...                    ...       ...       ...       ...       ...
393601         4256.148438  0.751434  0.177820  0.065010  0.005736
393602         3932.223633  0.690196  0.231373  0.056863  0.021569
393603         4376.018555  0.719682  0.202783  0.069583  0.007952
393604         3385.715687       NaN       NaN       NaN       NaN
393605         4785.799316  0.699588  0.228395  0.059671  0.012346

        envelhecidos_med  adultos_med  jovens_med  ate_fundamental_med  \
0               0.000000     0.000000    1.000000             0.500000
1               0.000000     0.000000    1.000000             0.000000
2               0.000000     0.000000    1.000000             0.750000
3               0.000000     0.200000    0.800000             0.200000
4               0.000000     0.000000    1.000000             0.000000
...                  ...          ...         ...                  ...
393601          0.036329     0.512428    0.451243             0.152964
393602          0.050980     0.554902    0.394118             0.131373
393603          0.037773     0.425447    0.536779             0.174950
393604          0.057391     0.540870    0.401739             0.120000
393605          0.034979     0.390947    0.574074             0.185185

        superior_med  rotatividade_med  mismatchover_med  mismatchunder_med  \
0           0.000000          0.000000          0.500000           0.000000
1           0.000000          0.000000          0.000000           0.000000
2           0.000000          0.000000          0.750000           0.000000
3           0.000000          0.000000          0.200000           0.000000
4           0.000000          0.000000          0.000000           0.000000
...              ...               ...               ...                ...
393601      0.135755          0.009560          0.172084           0.156788
393602      0.209804          0.011765          0.147059           0.135294
393603      0.161034          0.009940          0.182903           0.192843
393604      0.215652          0.017391          0.135652           0.151304
393605      0.176955          0.022634          0.156379           0.286008

        mismatchnull_med  tempo_emprego_a1_med  tempo_emprego_2a5_med  \
0               0.500000              0.500000               0.500000
1               1.000000              0.500000               0.000000
2               0.250000              0.750000               0.250000
3               0.800000              0.200000               0.600000
4               1.000000              1.000000               0.000000
...                  ...                   ...                    ...
393601          0.671128              0.080306               0.391969
393602          0.717647              0.131373               0.333333
393603          0.624254              0.147117               0.343936
393604          0.713043              0.224348               0.300870
393605          0.557613              0.154321               0.419753

        tempo_emprego_6mais_med  sal_hora_med  cbo_h1_med cbo_h2_med  \
0                      0.000000      5.165117    0.000000          0
1                      0.500000      9.383097    0.500000        NaN
2                      0.000000      8.335832    0.000000        NaN
3                      0.200000      7.744656    0.000000        NaN
4                      0.000000     11.214314    0.000000        NaN
...                         ...           ...         ...        ...
393601                 0.527725     24.471148    0.001912        NaN
393602                 0.535294     22.640743    0.005882        NaN
393603                 0.508946     25.156115    0.003976        NaN
393604                 0.474783           NaN         NaN        NaN
393605                 0.425926     27.420103    0.004115        NaN

        cbo_h3_med  sal_hora_dp  produtividade  data_abertura  \
0         1.000000     0.379776      20.660467       20052008
1         0.500000     4.946493      37.532386       20052008
2         0.750000     2.793418      33.343327       20052008
3         0.800000     2.955299      31.603609       20052008
4         0.000000          NaN      44.857258       20052008
...            ...          ...            ...            ...
393601    0.986616    16.885422      97.999718        2032005
393602    0.988235    15.209931      91.214142        2032005
393603    0.978131    18.036247     100.895554        2032005
393604         NaN          NaN      79.819046        2032005
393605    0.985597    19.770716     109.805420        2032005

        data_encerramento  municipio  natureza_juridica  qtd_vinc_atv  \
0                       0     313930               2135             1
1                       0     313930               2135             2
2                       0     313930               2135             4
3                       0     313930               2135             4
4                       0     313930               2135             1
...                   ...        ...                ...           ...
393601                  0     317010               2046           454
393602                  0     317010               2046           443
393603                  0     317010               2046           451
393604                  0     317010               2046           470
393605                  0     317010               2046           437

        ibge_subset  ind_atv_ano  cnae_20  nivel_tec  tamanho  idade  \
0                16            1       45          1        1    4.0
1                16            1       45          2        2    NaN
2                16            1       45          1        2    NaN
3                16            1       45          2        2    NaN
4                16            1       45          0        1    NaN
...             ...          ...      ...        ...      ...    ...
393601            7            1       16          4        5    NaN
393602            7            1       16          2        5    NaN
393603            7            1       16          1        5    NaN
393604            7            1       16          1        5    NaN
393605            7            1       16          1        5    NaN

        tamanho_2  setor_2  regiao   ano  firma  idade_med_quadrado  \
0             1.0      3.0     3.0  2011      1          650.250000
1             1.0      3.0     3.0  2021      1          676.000000
2             NaN      NaN     NaN  2015      1          495.062500
3             NaN      NaN     NaN  2019      1          665.639961
4             NaN      NaN     NaN  2013      1          529.000000
...           ...      ...     ...   ...    ...                 ...
393601        NaN      NaN     NaN  2017  65601         1327.160209
393602        NaN      NaN     NaN  2019  65601         1406.397060
393603        NaN      NaN     NaN  2015  65601         1227.506278
393604        5.0      1.0     3.0  2021  65601         1375.442344
393605        NaN      NaN     NaN  2013  65601         1199.496174

        sexo_raca_interacao  nivel_tec_1  nivel_tec_2  nivel_tec_3  \
0                  0.000000            1            0            0
1                  0.500000            0            1            0
2                  0.187500            1            0            0
3                  0.240000            0            1            0
4                  0.000000            0            0            0
...                     ...          ...          ...          ...
393601             0.012986            0            0            0
393602             0.019839            0            1            0
393603             0.016339            1            0            0
393604                  NaN            1            0            0
393605             0.017337            1            0            0

        nivel_tec_4  nivel_tec_5  d_2011  d_2013  d_2015  d_2017  d_2019  \
0                 0            0       1       0       0       0       0
1                 0            0       0       0       0       0       0
2                 0            0       0       0       1       0       0
3                 0            0       0       0       0       0       1
4                 0            0       0       1       0       0       0
...             ...          ...     ...     ...     ...     ...     ...
393601            1            0       0       0       0       1       0
393602            0            0       0       0       0       0       1
393603            0            0       0       0       1       0       0
393604            0            0       0       0       0       0       0
393605            0            0       0       1       0       0       0

        d_2021     y_log  nivel_tec_classificado
0            0  6.812412                       0
1            1  7.409394                       0
2            0  7.291047                       0
3            0  7.132100                       0
4            0  7.587675                       0
...        ...       ...                     ...
393601       0  8.356120                       0
393602       0  8.276960                       0
393603       0  8.383895                       0
393604       1  8.127321                       0
393605       0  8.473408                       0

[390780 rows x 58 columns]
--------------------------------------------------

DataFrame com a nova coluna 'ano_classificado':
        sexo_med  raca_cor_med  tempo_emprego_med  idade_med  \
0       0.000000      1.000000           9.450000  25.500000
1       1.000000      0.500000          53.300000  26.000000
2       0.250000      0.750000          10.925000  22.250000
3       0.400000      0.600000          40.939999  25.799999
4       1.000000      0.000000           6.900000  23.000000
...          ...           ...                ...        ...
393601  0.070746      0.183556          90.150864  36.430210
393602  0.078431      0.252941          94.140785  37.501961
393603  0.077535      0.210736          82.044731  35.035786
393604  0.126957           NaN          85.735652  37.086957
393605  0.072016      0.240741          74.588066  34.633743

        remun_med_real_med    hb_med    hn_med    mb_med    mn_med  \
0               909.060543  0.000000  1.000000  0.000000  0.000000
1              1651.425000  0.000000  0.000000  0.500000  0.500000
2              1467.106445  0.000000  0.750000  0.250000  0.000000
3              1251.502930  0.000000  0.600000  0.400000  0.000000
4              1973.719360  0.000000  0.000000  1.000000  0.000000
...                    ...       ...       ...       ...       ...
393601         4256.148438  0.751434  0.177820  0.065010  0.005736
393602         3932.223633  0.690196  0.231373  0.056863  0.021569
393603         4376.018555  0.719682  0.202783  0.069583  0.007952
393604         3385.715687       NaN       NaN       NaN       NaN
393605         4785.799316  0.699588  0.228395  0.059671  0.012346

        envelhecidos_med  adultos_med  jovens_med  ate_fundamental_med  \
0               0.000000     0.000000    1.000000             0.500000
1               0.000000     0.000000    1.000000             0.000000
2               0.000000     0.000000    1.000000             0.750000
3               0.000000     0.200000    0.800000             0.200000
4               0.000000     0.000000    1.000000             0.000000
...                  ...          ...         ...                  ...
393601          0.036329     0.512428    0.451243             0.152964
393602          0.050980     0.554902    0.394118             0.131373
393603          0.037773     0.425447    0.536779             0.174950
393604          0.057391     0.540870    0.401739             0.120000
393605          0.034979     0.390947    0.574074             0.185185

        superior_med  rotatividade_med  mismatchover_med  mismatchunder_med  \
0           0.000000          0.000000          0.500000           0.000000
1           0.000000          0.000000          0.000000           0.000000
2           0.000000          0.000000          0.750000           0.000000
3           0.000000          0.000000          0.200000           0.000000
4           0.000000          0.000000          0.000000           0.000000
...              ...               ...               ...                ...
393601      0.135755          0.009560          0.172084           0.156788
393602      0.209804          0.011765          0.147059           0.135294
393603      0.161034          0.009940          0.182903           0.192843
393604      0.215652          0.017391          0.135652           0.151304
393605      0.176955          0.022634          0.156379           0.286008

        mismatchnull_med  tempo_emprego_a1_med  tempo_emprego_2a5_med  \
0               0.500000              0.500000               0.500000
1               1.000000              0.500000               0.000000
2               0.250000              0.750000               0.250000
3               0.800000              0.200000               0.600000
4               1.000000              1.000000               0.000000
...                  ...                   ...                    ...
393601          0.671128              0.080306               0.391969
393602          0.717647              0.131373               0.333333
393603          0.624254              0.147117               0.343936
393604          0.713043              0.224348               0.300870
393605          0.557613              0.154321               0.419753

        tempo_emprego_6mais_med  sal_hora_med  cbo_h1_med cbo_h2_med  \
0                      0.000000      5.165117    0.000000          0
1                      0.500000      9.383097    0.500000        NaN
2                      0.000000      8.335832    0.000000        NaN
3                      0.200000      7.744656    0.000000        NaN
4                      0.000000     11.214314    0.000000        NaN
...                         ...           ...         ...        ...
393601                 0.527725     24.471148    0.001912        NaN
393602                 0.535294     22.640743    0.005882        NaN
393603                 0.508946     25.156115    0.003976        NaN
393604                 0.474783           NaN         NaN        NaN
393605                 0.425926     27.420103    0.004115        NaN

        cbo_h3_med  sal_hora_dp  produtividade  data_abertura  \
0         1.000000     0.379776      20.660467       20052008
1         0.500000     4.946493      37.532386       20052008
2         0.750000     2.793418      33.343327       20052008
3         0.800000     2.955299      31.603609       20052008
4         0.000000          NaN      44.857258       20052008
...            ...          ...            ...            ...
393601    0.986616    16.885422      97.999718        2032005
393602    0.988235    15.209931      91.214142        2032005
393603    0.978131    18.036247     100.895554        2032005
393604         NaN          NaN      79.819046        2032005
393605    0.985597    19.770716     109.805420        2032005

        data_encerramento  municipio  natureza_juridica  qtd_vinc_atv  \
0                       0     313930               2135             1
1                       0     313930               2135             2
2                       0     313930               2135             4
3                       0     313930               2135             4
4                       0     313930               2135             1
...                   ...        ...                ...           ...
393601                  0     317010               2046           454
393602                  0     317010               2046           443
393603                  0     317010               2046           451
393604                  0     317010               2046           470
393605                  0     317010               2046           437

        ibge_subset  ind_atv_ano  cnae_20  nivel_tec  tamanho  idade  \
0                16            1       45          1        1    4.0
1                16            1       45          2        2    NaN
2                16            1       45          1        2    NaN
3                16            1       45          2        2    NaN
4                16            1       45          0        1    NaN
...             ...          ...      ...        ...      ...    ...
393601            7            1       16          4        5    NaN
393602            7            1       16          2        5    NaN
393603            7            1       16          1        5    NaN
393604            7            1       16          1        5    NaN
393605            7            1       16          1        5    NaN

        tamanho_2  setor_2  regiao   ano  firma  idade_med_quadrado  \
0             1.0      3.0     3.0  2011      1          650.250000
1             1.0      3.0     3.0  2021      1          676.000000
2             NaN      NaN     NaN  2015      1          495.062500
3             NaN      NaN     NaN  2019      1          665.639961
4             NaN      NaN     NaN  2013      1          529.000000
...           ...      ...     ...   ...    ...                 ...
393601        NaN      NaN     NaN  2017  65601         1327.160209
393602        NaN      NaN     NaN  2019  65601         1406.397060
393603        NaN      NaN     NaN  2015  65601         1227.506278
393604        5.0      1.0     3.0  2021  65601         1375.442344
393605        NaN      NaN     NaN  2013  65601         1199.496174

        sexo_raca_interacao  nivel_tec_1  nivel_tec_2  nivel_tec_3  \
0                  0.000000            1            0            0
1                  0.500000            0            1            0
2                  0.187500            1            0            0
3                  0.240000            0            1            0

## Display Resumido do Dataframe

In [4]:
# Mostra as 10 primeiras linhas do dataframe

display(df)
display(dados_limpos_index[dados_limpos_index['tec_ano_interacao']==1])

,sexo_med,raca_cor_med,tempo_emprego_med,idade_med,remun_med_real_med,hb_med,hn_med,mb_med,mn_med,envelhecidos_med,adultos_med,jovens_med,ate_fundamental_med,superior_med,rotatividade_med,mismatchover_med,mismatchunder_med,mismatchnull_med,tempo_emprego_a1_med,tempo_emprego_2a5_med,tempo_emprego_6mais_med,sal_hora_med,cbo_h1_med,cbo_h2_med,cbo_h3_med,sal_hora_dp,produtividade,data_abertura,data_encerramento,municipio,natureza_juridica,qtd_vinc_atv,ibge_subset,ind_atv_ano,cnae_20,nivel_tec,tamanho,idade,tamanho_2,setor_2,regiao,ano,firma,idade_med_quadrado,sexo_raca_interacao,nivel_tec_1,nivel_tec_2,nivel_tec_3,nivel_tec_4,nivel_tec_5,d_2011,d_2013,d_2015,d_2017,d_2019,d_2021,y_log,nivel_tec_classificado,ano_classificado,tec_ano_interacao,mean_idade_med,mean_idade_med_quadrado,mean_sexo_med,mean_raca_cor_med,mean_superior_med,mean_sexo_raca_interacao,mean_nivel_tec_1,mean_nivel_tec_2,mean_nivel_tec_3,mean_nivel_tec_4,mean_nivel_tec_5,mean_d_2011,mean_d_2013,mean_d_2015,mean_d_2017,mean_d_2019,mean_d_2021
0,0.000000,1.000000,9.450000,25.500000,909.060543,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.000000,0.000000,0.500000,0.000000,0.500000,0.500000,0.500000,0.000000,5.165117,0.000000,0,1.000000,0.379776,20.660467,20052008,0,313930,2135,1,16,1,45,1,1,4.0,1.0,3.0,3.0,2011,1,650.250000,0.000000,1,0,0,0,0,1,0,0,0,0,0,6.812412,0,0,0,24.425000,598.658743,0.497222,0.586111,0.000000,0.191620,0.333333,0.500000,0.0,0.000000,0.0,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
1,1.000000,0.500000,53.300000,26.000000,1651.425000,0.000000,0.000000,0.500000,0.500000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.000000,0.500000,9.383097,0.500000,NaN,0.500000,4.946493,37.532386,20052008,0,313930,2135,2,16,1,45,2,2,NaN,1.0,3.0,3.0,2021,1,676.000000,0.500000,0,1,0,0,0,0,0,0,0,0,1,7.409394,0,1,0,24.425000,598.658743,0.497222,0.586111,0.000000,0.191620,0.333333,0.500000,0.0,0.000000,0.0,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
2,0.250000,0.750000,10.925000,22.250000,1467.106445,0.000000,0.750000,0.250000,0.000000,0.000000,0.000000,1.000000,0.750000,0.000000,0.000000,0.750000,0.000000,0.250000,0.750000,0.250000,0.000000,8.335832,0.000000,NaN,0.750000,2.793418,33.343327,20052008,0,313930,2135,4,16,1,45,1,2,NaN,NaN,NaN,NaN,2015,1,495.062500,0.187500,1,0,0,0,0,0,0,1,0,0,0,7.291047,0,0,0,24.425000,598.658743,0.497222,0.586111,0.000000,0.191620,0.333333,0.500000,0.0,0.000000,0.0,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
3,0.400000,0.600000,40.939999,25.799999,1251.502930,0.000000,0.600000,0.400000,0.000000,0.000000,0.200000,0.800000,0.200000,0.000000,0.000000,0.200000,0.000000,0.800000,0.200000,0.600000,0.200000,7.744656,0.000000,NaN,0.800000,2.955299,31.603609,20052008,0,313930,2135,4,16,1,45,2,2,NaN,NaN,NaN,NaN,2019,1,665.639961,0.240000,0,1,0,0,0,0,0,0,0,1,0,7.132100,0,0,0,24.425000,598.658743,0.497222,0.586111,0.000000,0.191620,0.333333,0.500000,0.0,0.000000,0.0,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
4,1.000000,0.000000,6.900000,23.000000,1973.719360,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,11.214314,0.000000,NaN,0.000000,NaN,44.857258,20052008,0,313930,2135,1,16,1,45,0,1,NaN,NaN,NaN,NaN,2013,1,529.000000,0.000000,0,0,0,0,0,0,1,0,0,0,0,7.587675,0,0,0,24.425000,598.658743,0.497222,0.586111,0.000000,0.191620,0.333333,0.500000,0.0,0.000000,0.0,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
393601,0.070746,0.183556,90.150864,36.430210,4256.148438,0.751434,0.177820,0.065010,0.005736,0.036329,0.512428,0.451243,0.152964,0.135755,0.009560,0.172084,0.156788,0.671128,0.080306,0.391969,0.527725,24.471148,0.001912,NaN,0.986616,16.885422,97.999718,2032005,0,317010,2046,454,7,1,16,4,5,NaN,NaN,NaN,NaN,2017,65601,1327.160209,0.012986,0,0,0,1,0,0,0,0,1,0,0,8.356120,0,0,0,35.727905,1278.377006,0.083057,0.226543,0.175361,0.016857,0.500000,0.166667,0.0,0.333333,0.0,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
393602,0.078431,0.252941,94.140785,37.501961,3932.223633,0.690196,0.231373,0.056863,0.021569,0.050980,0.554902,0.394118,0.131373,0.209804,0.011765,0.147059,0.135294,0.717647,0.131373,0.333333,0.535294,22.640743,0.005882,NaN,0.988235,15.209931,91.214142,2032005,0,317010,2046,443,7,1,16,2,5,NaN,NaN,NaN,NaN,2019,65601,1406.397060,0.019839,0,1,0,0,0,0,0,0,0,1,0,8.276960,0,0,0,35.727905,1278.377006,0.083057,0.226543,0.175361,0.016857,0.500000,0.166667,0.0,0.333333,0.0,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
393603,0.077535,0.210736,82.044731,35.035786,4376.018555,0.719682,0.202783,0.069583,0.007952,0.037773,0.425447,0.536779,0.174950,0.161034,0.009940,0.182903,0.192843,0.624254,0.147117,0.343936,0.508946,25.156115,0.003976,NaN,0.978131,18.036247,100.895554,2032005,0,317010,2046,451,7,1,16,1,5,NaN,NaN,NaN,NaN,2015,65601,1227.506278,0.016339,1,0,0,0,0,0,0,1,0,0,0,8.383895,0,0,0,35.727905,1278.377006,0.083057,0.226543,0.175361,0.016857,0.500000,0.166667,0.0,0.333333,0.0,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
393604,0.126957,NaN,85.735652,37.086957,3385.715687,NaN,NaN,NaN,NaN,0.057391,0.540870,0.401739,0.120000,0.215652,0.017391,0.135652,0.151304,0.713043,0.224348,0.300870,0.474783,NaN,NaN,NaN,NaN,NaN,79.819046,2032005,0,317010,2046,470,7,1,16,1,5,NaN,5.0,1.0,3.0,2021,65601,1375.442344,NaN,1,0,0,0,0,0,0,0,0,0,1,8.127321,0,1,0,35.727905,1278.377006,0.083057,0.226543,0.175361,0.016857,0.500000,0.166667,0.0,0.333333,0.0,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667
393605,0.072016,0.240741,74.588066,34.633743,4785.799316,0.699588,0.228395,0.059671,0.012346,0.034979,0.390947,0.574074,0.185185,0.176955,0.022634,0.156379,0.286008,0.557613,0.154321,0.419753,0.425926,27.420103,0.004115,NaN,0.985597,19.770716,109.805420,2032005,0,317010,2046,437,7,1,16,1,5,NaN,NaN,NaN,NaN,2013,65601,1199.496174,0.017337,1,0,0,0,0,0,1,0,0,0,0,8.473408,0,0,0,35.727905,1278.377006,0.083057,0.226543,0.175361,0.016857,0.500000,0.166667,0.0,0.333333,0.0,0.166667,0.166667,0.166667,0.166667,0.166667,0.166667

,,y_log,adultos_med,idade_med,superior_med,idade_med_quadrado,sexo_med,raca_cor_med,sexo_raca_interacao,nivel_tec_1,nivel_tec_2,nivel_tec_3,nivel_tec_4,nivel_tec_5,ano_classificado,nivel_tec_classificado,tec_ano_interacao,remun_med_real_med
firma,ano,,,,,,,,,,,,,,,,,
161,2021,7.088937,0.333333,46.666667,0.000000,2177.777778,0.500000,1.000000,0.500000,0,0,0,0,1,1,1,1,1198.633333
273,2021,8.040411,0.714286,39.000000,0.142857,1521.000000,0.714286,0.428571,0.306122,0,0,0,0,1,1,1,1,3103.890000
670,2021,7.691000,0.000000,25.000000,0.000000,625.000000,0.066667,0.533333,0.035556,0,0,0,0,1,1,1,1,2188.561333
1207,2021,7.060442,0.000000,27.666667,0.000000,765.444444,0.333333,0.000000,0.000000,0,0,0,0,1,1,1,1,1164.960000
1208,2021,7.105195,0.363636,34.227273,0.909091,1171.506198,0.500000,0.000000,0.000000,0,0,0,0,1,1,1,1,1218.280000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65362,2021,8.373584,0.416667,38.250000,0.833333,1463.062500,0.500000,0.000000,0.000000,0,0,0,0,1,1,1,1,4331.129167
65363,2021,8.524236,0.545455,38.772727,0.818182,1503.324380,0.500000,0.136364,0.068182,0,0,0,0,1,1,1,1,5035.338182
65393,2021,8.469127,0.272727,32.636364,0.818182,1065.132231,0.636364,0.363636,0.231405,0,0,0,0,1,1,1,1,4765.351818
65473,2021,7.256173,0.818182,44.090909,0.000000,1944.008264,0.272727,0.818182,0.223140,0,0,0,0,1,1,1,1,1416.824545
65509,2021,7.562349,0.000000,34.000000,0.000000,1156.000000,1.000000,0.000000,0.000000,0,0,0,0,1,1,1,1,1924.360000

## Análise Exploratória

### Descrição das Variáveis

In [5]:
# Gera estatísticas descritivas das principais variáveis

print('--------------------------------------------------------------------------')
desc_stats = dados_limpos.describe()
print(desc_stats)
print('--------------------------------------------------------------------------')

# Supondo que df seja seu DataFrame
quantidade_zeros = (df['remun_med_real_med'] == 0).sum()

print(f"Existem {quantidade_zeros} valores zerados na coluna remun_med_real_med")

--------------------------------------------------------------------------
               firma            ano          y_log    adultos_med  \
count  311862.000000  311862.000000  311862.000000  311862.000000
mean    32942.299100    2015.611751       7.361490       0.387261
std     18939.566705       3.365059       0.431398       0.289893
min         1.000000    2011.000000       2.486937       0.000000
25%     16528.000000    2013.000000       7.080621       0.166667
50%     33043.500000    2015.000000       7.262308       0.363636
75%     49546.000000    2019.000000       7.540576       0.534247
max     65601.000000    2021.000000      11.754593       1.000000

           idade_med   superior_med  idade_med_quadrado       sexo_med  \
count  311862.000000  311862.000000       311862.000000  311862.000000
mean       35.218499       0.087056         1300.904121       0.463178
std         7.782137       0.195953          595.960079       0.364316
min        18.000000       0.000000          324.000000       0.000000
25%        29.799999       0.000000          888.039955       0.111111
50%        34.375000       0.000000         1181.640625       0.444444
75%        39.666668       0.065778         1573.444545       0.800000
max        75.000000       1.000000         5625.000000       1.000000

        raca_cor_med  sexo_raca_interacao    nivel_tec_1    nivel_tec_2  \
count  311862.000000        311862.000000  311862.000000  311862.000000
mean        0.351590             0.156741       0.261895       0.165663
std         0.359495             0.246651       0.439666       0.371778
min         0.000000             0.000000       0.000000       0.000000
25%         0.000000             0.000000       0.000000       0.000000
50%         0.250000             0.030000       0.000000       0.000000
75%         0.631579             0.222222       1.000000       0.000000
max         1.000000             1.000000       1.000000       1.000000

         nivel_tec_3    nivel_tec_4    nivel_tec_5  ano_classificado  \
count  311862.000000  311862.000000  311862.000000     311862.000000
mean        0.031549       0.044696       0.012967          0.134774
std         0.174797       0.206636       0.113133          0.341483
min         0.000000       0.000000       0.000000          0.000000
25%         0.000000       0.000000       0.000000          0.000000
50%         0.000000       0.000000       0.000000          0.000000
75%         0.000000       0.000000       0.000000          0.000000
max         1.000000       1.000000       1.000000          1.000000

       nivel_tec_classificado  tec_ano_interacao  remun_med_real_med
count           311862.000000      311862.000000       311862.000000
mean                 0.012967           0.001667         1771.316813
std                  0.113133           0.040800         1296.408838
min                  0.000000           0.000000           12.024386
25%                  0.000000           0.000000         1188.706890
50%                  0.000000           0.000000         1425.543457
75%                  0.000000           0.000000         1882.914612
max                  1.000000           1.000000       127337.085708
--------------------------------------------------------------------------
Existem 0 valores zerados na coluna remun_med_real_med

### Analisando modelos

#### Modelo Pooled

In [6]:
# Criação das variáveis X e Y utilizadas nos modelos

X_sem_constante = dados_limpos_index.drop(columns=['y_log', 'adultos_med'])
X = sm.add_constant(X_sem_constante[['idade_med', 'superior_med', 'idade_med_quadrado', 'sexo_med', 'raca_cor_med', 'sexo_raca_interacao', 'nivel_tec_1', 'nivel_tec_2', 'nivel_tec_3', 'nivel_tec_4', 'nivel_tec_5']])
Y = dados_limpos_index[['y_log']]

# ==============================================
# 1. MODELO POOLED OLS
# ==============================================
modelo_pooled = PooledOLS(dependent=Y, exog=X).fit()
print(modelo_pooled.summary)

# ==============================================
# 2. TESTE DE HETEROCEDASTICIDADE (BREUSCH-PAGAN)
# ==============================================
residuals = modelo_pooled.resids.values.flatten()

if isinstance(X, pd.DataFrame):
    exog = X.values
else:
    try:
        exog = X.dataframe.values
    except AttributeError:
        exog = X.values

teste_bp = het_breuschpagan(residuals, exog)

labels_bp = ['Estatística LM', 'Valor-p LM', 'Estatística F', 'Valor-p F']
resultados_bp = dict(zip(labels_bp, teste_bp))

print("\n=== TESTE DE BREUSCH-PAGAN ===")
for key, value in resultados_bp.items():
    print(f"{key}: {value:.4f}")

# ==============================================
# 3. TESTE DE AUTOCORRELAÇÃO
# ==============================================
# Para PooledOLS, verificamos autocorrelação geral (não por entidade)
residuals = modelo_pooled.resids
resid_df = pd.DataFrame({'residuos': residuals})

# Calcular estatística de Durbin-Watson
dw = np.sum(np.diff(residuals)**2) / np.sum(residuals**2)

print("\n=== TESTE DE AUTOCORRELAÇÃO ===")
print(f"Estatística de Durbin-Watson: {dw:.4f}")

# Interpretação
print("\nInterpretação:")
print("≈2: sem autocorrelação")
print("<1.5: possível autocorrelação positiva")
print(">2.5: possível autocorrelação negativa")

# ==============================================
# 4. TESTE DE MULTICOLINEARIDADE (VIF)
# ==============================================
if isinstance(X, pd.DataFrame):
    vif = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
    print("\n=== FATOR DE INFLACÃO DE VARIÂNCIA (VIF) ===")
    for i, col in enumerate(X.columns):
        print(f"{col}: VIF = {vif[i]:.2f}")
else:
    print("\nAVISO: VIF não calculado - X precisa ser um DataFrame")

# ==============================================
# 5. VERSÃO COM ERROS ROBUSTOS (OPCIONAL)
# ==============================================
print("\n=== VERSÃO COM ERROS ROBUSTOS ===")
modelo_robusto = PooledOLS(dependent=Y, exog=X).fit(cov_type='robust')
print(modelo_robusto.summary)

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:                  y_log   R-squared:                        0.3256
Estimator:                  PooledOLS   R-squared (Between):              0.3940
No. Observations:              311862   R-squared (Within):              -0.1618
Date:                Fri, Jun 27 2025   R-squared (Overall):              0.3256
Time:                        08:02:09   Log-likelihood                -1.189e+05
Cov. Estimator:            Unadjusted
                                        F-statistic:                   1.369e+04
Entities:                       63239   P-value                           0.0000
Avg Obs:                       4.9315   Distribution:               F(11,311850)
Min Obs:                       1.0000
Max Obs:                       6.0000   F-statistic (robust):          1.369e+04
                                        P-value                           0.0000
Time periods:                       6   Distribution:               F(11,311850)
Avg Obs:                    5.198e+04
Min Obs:                    4.203e+04
Max Obs:                     5.94e+04

                                  Parameter Estimates
=======================================================================================
                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------
const                   6.4625     0.0102     632.89     0.0000      6.4425      6.4825
idade_med               0.0445     0.0005     82.018     0.0000      0.0434      0.0456
superior_med            1.0839     0.0033     326.50     0.0000      1.0774      1.0905
idade_med_quadrado     -0.0005  7.065e-06    -73.073     0.0000     -0.0005     -0.0005
sexo_med               -0.2590     0.0024    -108.69     0.0000     -0.2637     -0.2543
raca_cor_med           -0.0087     0.0028    -3.1539     0.0016     -0.0141     -0.0033
sexo_raca_interacao     0.0283     0.0046     6.1906     0.0000      0.0194      0.0373
nivel_tec_1             0.0555     0.0016     35.209     0.0000      0.0524      0.0586
nivel_tec_2             0.0510     0.0018     27.741     0.0000      0.0474      0.0546
nivel_tec_3             0.0495     0.0037     13.360     0.0000      0.0422      0.0567
nivel_tec_4             0.0542     0.0032     17.176     0.0000      0.0480      0.0603
nivel_tec_5             0.0556     0.0057     9.8273     0.0000      0.0445      0.0667
=======================================================================================

=== TESTE DE BREUSCH-PAGAN ===
Estatística LM: 36043.7106
Valor-p LM: 0.0000
Estatística F: 3704.7550
Valor-p F: 0.0000

=== TESTE DE AUTOCORRELAÇÃO ===
Estatística de Durbin-Watson: 0.8211

Interpretação:
≈2: sem autocorrelação
<1.5: possível autocorrelação positiva
>2.5: possível autocorrelação negativa

=== FATOR DE INFLACÃO DE VARIÂNCIA (VIF) ===
const: VIF = 259.08
idade_med: VIF = 44.29
superior_med: VIF = 1.05
idade_med_quadrado: VIF = 44.04
sexo_med: VIF = 1.87
raca_cor_med: VIF = 2.44
sexo_raca_interacao: VIF = 3.16
nivel_tec_1: VIF = 1.19
nivel_tec_2: VIF = 1.16
nivel_tec_3: VIF = 1.04
nivel_tec_4: VIF = 1.05
nivel_tec_5: VIF = 1.02

=== VERSÃO COM ERROS ROBUSTOS ===
                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:                  y_log   R-squared:                        0.3256
Estimator:                  PooledOLS   R-squared (Between):              0.3940
No. Observations:              311862   R-squared (Within):              -0.1618
Date:                Fri, Jun 27 2025   R-squared (Overall):              0.3256
Time:                        08:02:13   Log-likelihood                -1.189e+05
Cov. Estimator:                Robust
                                        F-statistic:                   1.369e+04
Entities:                       63239   P-value                           0.0000
Avg Obs:                       4.9315   Distribution:               F(11,311850)
Min Obs:                       1.0000
Max Obs:                       6.0000   F-statistic (robust):             6643.6
                                        P-value                           0.0000
Time periods:                       6   Distribution:               F(11,311850)
Avg Obs:                    5.198e+04
Min Obs:                    4.203e+04
Max Obs:                     5.94e+04

                                  Parameter Estimates
=======================================================================================
                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------
const                   6.4625     0.0110     588.31     0.0000      6.4410      6.4840
idade_med               0.0445     0.0006     72.071     0.0000      0.0433      0.0457
superior_med            1.0839     0.0062     176.14     0.0000      1.0719      1.0960
idade_med_quadrado     -0.0005  8.506e-06    -60.689     0.0000     -0.0005     -0.0005
sexo_med               -0.2590     0.0024    -107.69     0.0000     -0.2637     -0.2543
raca_cor_med           -0.0087     0.0028    -3.1101     0.0019     -0.0142     -0.0032
sexo_raca_interacao     0.0283     0.0044     6.3705     0.0000      0.0196      0.0370
nivel_tec_1             0.0555     0.0016     34.731     0.0000      0.0523      0.0586
nivel_tec_2             0.0510     0.0019     26.721     0.0000      0.0472      0.0547
nivel_tec_3             0.0495     0.0041     12.063     0.0000      0.0414      0.0575
nivel_tec_4             0.0542     0.0034     15.890     0.0000      0.0475      0.0608
nivel_tec_5             0.0556     0.0062     8.9282     0.0000      0.0434      0.0678
=======================================================================================

#### Modelo considerando os efeitos fixos

In [7]:
# ==============================================
# 1. MODELO DE EFEITOS FIXOS
# ==============================================
efeitos_fixos = PanelOLS(Y, X, entity_effects=True).fit()
print(efeitos_fixos.summary)

# ==============================================
# 2. TESTE DE HETEROCEDASTICIDADE (BREUSCH-PAGAN)
# ==============================================
residuals = efeitos_fixos.resids.values.flatten()

if isinstance(X, pd.DataFrame):
    exog = X.values
else:
    try:
        exog = X.dataframe.values
    except AttributeError:
        exog = X.values

teste_bp = het_breuschpagan(residuals, exog)

labels_bp = ['Estatística LM', 'Valor-p LM', 'Estatística F', 'Valor-p F']
resultados_bp = dict(zip(labels_bp, teste_bp))

print("\n=== TESTE DE BREUSCH-PAGAN ===")
for key, value in resultados_bp.items():
    print(f"{key}: {value:.4f}")

# ==============================================
# 3. TESTE DE AUTOCORRELAÇÃO SIMPLIFICADO
# ==============================================
# Extrair resíduos e índices diretamente
residuals = efeitos_fixos.resids
resid_df = residuals.to_frame(name='residuos')
resid_df['entidade'] = resid_df.index.get_level_values(0)  # Assume que o primeiro nível é a entidade

# Calcular autocorrelação por entidade
autocorr_results = resid_df.groupby('entidade')['residuos'].apply(
    lambda x: x.autocorr(lag=1)  # Autocorrelação de 1ª ordem
)

print("\n=== TESTE DE AUTOCORRELAÇÃO ===")
print("Autocorrelação de 1ª ordem por entidade:")
print(autocorr_results)
print(f"\nAutocorrelação média: {autocorr_results.mean():.4f}")

# Interpretação
print("\nInterpretação:")
print("Valor próximo de 0: sem autocorrelação")
print("Valor positivo (>0.2): autocorrelação positiva")
print("Valor negativo (<-0.2): autocorrelação negativa")

# ==============================================
# 4. TESTE DE MULTICOLINEARIDADE (VIF)
# ==============================================
if isinstance(X, pd.DataFrame):
    vif = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
    print("\n=== FATOR DE INFLACÃO DE VARIÂNCIA (VIF) ===")
    for i, col in enumerate(X.columns):
        print(f"{col}: VIF = {vif[i]:.2f}")
else:
    print("\nAVISO: VIF não calculado - X precisa ser um DataFrame")

# ==============================================
# 5. MODELO DE EFEITOS FIXOS (CORRIGIDO)
# ==============================================
efeitos_fixos = PanelOLS(Y, X, entity_effects=True).fit(cov_type='clustered', cluster_entity=True)
print(efeitos_fixos.summary)

                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                  y_log   R-squared:                        0.0589
Estimator:                   PanelOLS   R-squared (Between):              0.1765
No. Observations:              311862   R-squared (Within):               0.0589
Date:                Fri, Jun 27 2025   R-squared (Overall):              0.1635
Time:                        08:02:18   Log-likelihood                 1.278e+05
Cov. Estimator:            Unadjusted
                                        F-statistic:                      1413.6
Entities:                       63239   P-value                           0.0000
Avg Obs:                       4.9315   Distribution:               F(11,248612)
Min Obs:                       1.0000
Max Obs:                       6.0000   F-statistic (robust):             1413.6
                                        P-value                           0.0000
Time periods:                       6   Distribution:               F(11,248612)
Avg Obs:                    5.198e+04
Min Obs:                    4.203e+04
Max Obs:                     5.94e+04

                                  Parameter Estimates
=======================================================================================
                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------
const                   6.7884     0.0083     822.15     0.0000      6.7722      6.8046
idade_med               0.0275     0.0004     63.753     0.0000      0.0266      0.0283
superior_med            0.2781     0.0036     78.089     0.0000      0.2711      0.2850
idade_med_quadrado     -0.0003  5.585e-06    -51.991     0.0000     -0.0003     -0.0003
sexo_med               -0.0860     0.0028    -30.911     0.0000     -0.0914     -0.0805
raca_cor_med           -0.0127     0.0027    -4.7709     0.0000     -0.0178     -0.0075
sexo_raca_interacao     0.0143     0.0040     3.5507     0.0004      0.0064      0.0222
nivel_tec_1             0.0009     0.0019     0.4652     0.6418     -0.0028      0.0045
nivel_tec_2             0.0014     0.0019     0.7178     0.4729     -0.0024      0.0052
nivel_tec_3             0.0018     0.0027     0.6738     0.5005     -0.0034      0.0070
nivel_tec_4             0.0024     0.0024     0.9963     0.3191     -0.0023      0.0072
nivel_tec_5             0.0048     0.0036     1.3320     0.1829     -0.0023      0.0119
=======================================================================================

F-test for Poolability: 15.195
P-value: 0.0000
Distribution: F(63238,248612)

Included effects: Entity

=== TESTE DE BREUSCH-PAGAN ===
Estatística LM: 1626.7306
Valor-p LM: 0.0000
Estatística F: 148.6543
Valor-p F: 0.0000

/home/ph-padrim/Área de trabalho/Trabalho de Econometria/trabalho 2/novo_venv/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py:3055: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/home/ph-padrim/Área de trabalho/Trabalho de Econometria/trabalho 2/novo_venv/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py:2912: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/home/ph-padrim/Área de trabalho/Trabalho de Econometria/trabalho 2/novo_venv/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py:2912: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

=== TESTE DE AUTOCORRELAÇÃO ===
Autocorrelação de 1ª ordem por entidade:
entidade
1       -0.644078
2       -0.257701
4       -1.000000
5       -0.880772
6       -0.530960
           ...
65597   -0.252398
65598    0.474782
65599   -0.028057
65600   -0.475670
65601    0.065501
Name: residuos, Length: 63239, dtype: float64

Autocorrelação média: -0.2083

Interpretação:
Valor próximo de 0: sem autocorrelação
Valor positivo (>0.2): autocorrelação positiva
Valor negativo (<-0.2): autocorrelação negativa

=== FATOR DE INFLACÃO DE VARIÂNCIA (VIF) ===
const: VIF = 259.08
idade_med: VIF = 44.29
superior_med: VIF = 1.05
idade_med_quadrado: VIF = 44.04
sexo_med: VIF = 1.87
raca_cor_med: VIF = 2.44
sexo_raca_interacao: VIF = 3.16
nivel_tec_1: VIF = 1.19
nivel_tec_2: VIF = 1.16
nivel_tec_3: VIF = 1.04
nivel_tec_4: VIF = 1.05
nivel_tec_5: VIF = 1.02
                          PanelOLS Estimation Summary
================================================================================
Dep. Variable:                  y_log   R-squared:                        0.0589
Estimator:                   PanelOLS   R-squared (Between):              0.1765
No. Observations:              311862   R-squared (Within):               0.0589
Date:                Fri, Jun 27 2025   R-squared (Overall):              0.1635
Time:                        08:02:34   Log-likelihood                 1.278e+05
Cov. Estimator:             Clustered
                                        F-statistic:                      1413.6
Entities:                       63239   P-value                           0.0000
Avg Obs:                       4.9315   Distribution:               F(11,248612)
Min Obs:                       1.0000
Max Obs:                       6.0000   F-statistic (robust):             542.87
                                        P-value                           0.0000
Time periods:                       6   Distribution:               F(11,248612)
Avg Obs:                    5.198e+04
Min Obs:                    4.203e+04
Max Obs:                     5.94e+04

                                  Parameter Estimates
=======================================================================================
                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------
const                   6.7884     0.0127     533.90     0.0000      6.7635      6.8133
idade_med               0.0275     0.0007     38.658     0.0000      0.0261      0.0289
superior_med            0.2781     0.0076     36.700     0.0000      0.2632      0.2929
idade_med_quadrado     -0.0003  9.816e-06    -29.581     0.0000     -0.0003     -0.0003
sexo_med               -0.0860     0.0043    -19.956     0.0000     -0.0944     -0.0775
raca_cor_med           -0.0127     0.0038    -3.3292     0.0009     -0.0201     -0.0052
sexo_raca_interacao     0.0143     0.0056     2.5649     0.0103      0.0034      0.0252
nivel_tec_1             0.0009     0.0020     0.4268     0.6695     -0.0031      0.0048
nivel_tec_2             0.0014     0.0021     0.6695     0.5032     -0.0027      0.0055
nivel_tec_3             0.0018     0.0029     0.6243     0.5324     -0.0038      0.0074
nivel_tec_4             0.0024     0.0026     0.9382     0.3482     -0.0026      0.0075
nivel_tec_5             0.0048     0.0036     1.3193     0.1871     -0.0023      0.0119
=======================================================================================

F-test for Poolability: 15.195
P-value: 0.0000
Distribution: F(63238,248612)

Included effects: Entity

#### Modelo considerando os efeitos aleatórios

In [8]:
# ==============================================
# 1. MODELO DE EFEITOS ALEATÓRIOS
# ==============================================
modelo_re = RandomEffects(Y, X).fit()
print(modelo_re.summary)

# ==============================================
# 2. TESTE DE HETEROCEDASTICIDADE (BREUSCH-PAGAN)
# ==============================================
residuals = modelo_re.resids.values.flatten()

if isinstance(X, pd.DataFrame):
    exog = X.values
else:
    try:
        exog = X.dataframe.values
    except AttributeError:
        exog = X.values

teste_bp = het_breuschpagan(residuals, exog)

labels_bp = ['Estatística LM', 'Valor-p LM', 'Estatística F', 'Valor-p F']
resultados_bp = dict(zip(labels_bp, teste_bp))

print("\n=== TESTE DE BREUSCH-PAGAN ===")
for key, value in resultados_bp.items():
    print(f"{key}: {value:.4f}")

# ==============================================
# 3. TESTE DE AUTOCORRELAÇÃO
# ==============================================
# Extrair resíduos e índices
residuals = modelo_re.resids
resid_df = residuals.to_frame(name='residuos')
resid_df['entidade'] = resid_df.index.get_level_values(0)  # Assume primeiro nível é entidade

# Calcular autocorrelação por entidade
autocorr_results = resid_df.groupby('entidade')['residuos'].apply(
    lambda x: x.autocorr(lag=1)  # Autocorrelação de 1ª ordem
)

print("\n=== TESTE DE AUTOCORRELAÇÃO ===")
print("Autocorrelação de 1ª ordem por entidade:")
print(autocorr_results)
print(f"\nAutocorrelação média: {autocorr_results.mean():.4f}")

# Interpretação
print("\nInterpretação:")
print("Valor próximo de 0: sem autocorrelação")
print("Valor positivo (>0.2): autocorrelação positiva")
print("Valor negativo (<-0.2): autocorrelação negativa")

# ==============================================
# 4. TESTE DE MULTICOLINEARIDADE (VIF)
# ==============================================
if isinstance(X, pd.DataFrame):
    vif = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]
    print("\n=== FATOR DE INFLACÃO DE VARIÂNCIA (VIF) ===")
    for i, col in enumerate(X.columns):
        print(f"{col}: VIF = {vif[i]:.2f}")
else:
    print("\nAVISO: VIF não calculado - X precisa ser um DataFrame")

# ==============================================
# 5. MODELO DE EFEITOS ALEATÓRIOS (CORRIGIDO)
# ==============================================
modelo_re = RandomEffects(Y, X).fit(cov_type='clustered', cluster_entity=True)
print(modelo_re.summary)

                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:                  y_log   R-squared:                        0.7305
Estimator:              RandomEffects   R-squared (Between):              0.2657
No. Observations:              311862   R-squared (Within):               0.0434
Date:                Fri, Jun 27 2025   R-squared (Overall):              0.2403
Time:                        08:02:41   Log-likelihood                 8.341e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                   7.685e+04
Entities:                       63239   P-value                           0.0000
Avg Obs:                       4.9315   Distribution:               F(11,311850)
Min Obs:                       1.0000
Max Obs:                       6.0000   F-statistic (robust):             3416.4
                                        P-value                           0.0000
Time periods:                       6   Distribution:               F(11,311850)
Avg Obs:                    5.198e+04
Min Obs:                    4.203e+04
Max Obs:                     5.94e+04

                                  Parameter Estimates
=======================================================================================
                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------
const                   6.7197     0.0081     826.25     0.0000      6.7038      6.7356
idade_med               0.0310     0.0004     73.357     0.0000      0.0301      0.0318
superior_med            0.4791     0.0033     145.79     0.0000      0.4727      0.4856
idade_med_quadrado     -0.0003  5.481e-06    -61.383     0.0000     -0.0003     -0.0003
sexo_med               -0.1406     0.0025    -57.008     0.0000     -0.1454     -0.1357
raca_cor_med           -0.0106     0.0025    -4.2269     0.0000     -0.0155     -0.0057
sexo_raca_interacao     0.0118     0.0039     3.0296     0.0024      0.0041      0.0194
nivel_tec_1             0.0359     0.0016     22.273     0.0000      0.0327      0.0391
nivel_tec_2             0.0359     0.0017     21.074     0.0000      0.0325      0.0392
nivel_tec_3             0.0358     0.0025     14.187     0.0000      0.0308      0.0407
nivel_tec_4             0.0372     0.0023     16.442     0.0000      0.0328      0.0416
nivel_tec_5             0.0389     0.0035     10.998     0.0000      0.0320      0.0458
=======================================================================================

=== TESTE DE BREUSCH-PAGAN ===
Estatística LM: 5393.3885
Valor-p LM: 0.0000
Estatística F: 498.9175
Valor-p F: 0.0000

/home/ph-padrim/Área de trabalho/Trabalho de Econometria/trabalho 2/novo_venv/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py:3055: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/home/ph-padrim/Área de trabalho/Trabalho de Econometria/trabalho 2/novo_venv/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py:2912: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/home/ph-padrim/Área de trabalho/Trabalho de Econometria/trabalho 2/novo_venv/lib/python3.12/site-packages/numpy/lib/_function_base_impl.py:2912: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

=== TESTE DE AUTOCORRELAÇÃO ===
Autocorrelação de 1ª ordem por entidade:
entidade
1       -0.639960
2       -0.261381
4       -1.000000
5       -0.927560
6       -0.567297
           ...
65597   -0.393908
65598    0.117879
65599   -0.076308
65600   -0.446626
65601    0.011395
Name: residuos, Length: 63239, dtype: float64

Autocorrelação média: -0.2094

Interpretação:
Valor próximo de 0: sem autocorrelação
Valor positivo (>0.2): autocorrelação positiva
Valor negativo (<-0.2): autocorrelação negativa

=== FATOR DE INFLACÃO DE VARIÂNCIA (VIF) ===
const: VIF = 259.08
idade_med: VIF = 44.29
superior_med: VIF = 1.05
idade_med_quadrado: VIF = 44.04
sexo_med: VIF = 1.87
raca_cor_med: VIF = 2.44
sexo_raca_interacao: VIF = 3.16
nivel_tec_1: VIF = 1.19
nivel_tec_2: VIF = 1.16
nivel_tec_3: VIF = 1.04
nivel_tec_4: VIF = 1.05
nivel_tec_5: VIF = 1.02
                        RandomEffects Estimation Summary
================================================================================
Dep. Variable:                  y_log   R-squared:                        0.7305
Estimator:              RandomEffects   R-squared (Between):              0.2657
No. Observations:              311862   R-squared (Within):               0.0434
Date:                Fri, Jun 27 2025   R-squared (Overall):              0.2403
Time:                        08:02:58   Log-likelihood                 8.341e+04
Cov. Estimator:             Clustered
                                        F-statistic:                   7.685e+04
Entities:                       63239   P-value                           0.0000
Avg Obs:                       4.9315   Distribution:               F(11,311850)
Min Obs:                       1.0000
Max Obs:                       6.0000   F-statistic (robust):             1177.0
                                        P-value                           0.0000
Time periods:                       6   Distribution:               F(11,311850)
Avg Obs:                    5.198e+04
Min Obs:                    4.203e+04
Max Obs:                     5.94e+04

                                  Parameter Estimates
=======================================================================================
                     Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
---------------------------------------------------------------------------------------
const                   6.7197     0.0120     560.27     0.0000      6.6962      6.7432
idade_med               0.0310     0.0007     45.876     0.0000      0.0296      0.0323
superior_med            0.4791     0.0076     63.132     0.0000      0.4642      0.4940
idade_med_quadrado     -0.0003   9.38e-06    -35.868     0.0000     -0.0004     -0.0003
sexo_med               -0.1406     0.0035    -40.210     0.0000     -0.1474     -0.1337
raca_cor_med           -0.0106     0.0034    -3.0966     0.0020     -0.0173     -0.0039
sexo_raca_interacao     0.0118     0.0052     2.2779     0.0227      0.0016      0.0219
nivel_tec_1             0.0359     0.0017     20.857     0.0000      0.0325      0.0393
nivel_tec_2             0.0359     0.0018     20.020     0.0000      0.0324      0.0394
nivel_tec_3             0.0358     0.0027     13.331     0.0000      0.0305      0.0410
nivel_tec_4             0.0372     0.0024     15.802     0.0000      0.0326      0.0418
nivel_tec_5             0.0389     0.0035     11.068     0.0000      0.0320      0.0458
=======================================================================================

#### Teste entre Pooled x Efeitos fixos

In [9]:
from linearmodels.panel import compare  
pvalue_ftest = efeitos_fixos.f_pooled  # p-valor do teste F  
print(f"P-valor (FE vs. Pooled): {pvalue_ftest}")  

# Será usado efeitos fixos

P-valor (FE vs. Pooled): Pooled F-statistic
H0: Effects are zero
Statistic: 15.1947
P-value: 0.0000
Distributed: F(63238,248612)

#### Teste de Hausman (Efeitos fixos X Efeitos aleatórios)

In [10]:
hausman = compare({'FE': efeitos_fixos, 'RE': modelo_re}, precision='tstats')
print(hausman)

# Será usado efeitos fixos

                    Model Comparison
=======================================================
                                   FE                RE
-------------------------------------------------------
Dep. Variable                   y_log             y_log
Estimator                    PanelOLS     RandomEffects
No. Observations               311862            311862
Cov. Est.                   Clustered         Clustered
R-squared                      0.0589            0.7305
R-Squared (Within)             0.0589            0.0434
R-Squared (Between)            0.1765            0.2657
R-Squared (Overall)            0.1635            0.2403
F-statistic                    1413.6         7.685e+04
P-value (F-stat)               0.0000            0.0000
=====================     ===========   ===============
const                          6.7884            6.7197
                             (533.90)          (560.27)
idade_med                      0.0275            0.0310
                             (38.658)          (45.876)
superior_med                   0.2781            0.4791
                             (36.700)          (63.132)
idade_med_quadrado            -0.0003           -0.0003
                            (-29.581)         (-35.868)
sexo_med                      -0.0860           -0.1406
                            (-19.956)         (-40.210)
raca_cor_med                  -0.0127           -0.0106
                            (-3.3292)         (-3.0966)
sexo_raca_interacao            0.0143            0.0118
                             (2.5649)          (2.2779)
nivel_tec_1                    0.0009            0.0359
                             (0.4268)          (20.857)
nivel_tec_2                    0.0014            0.0359
                             (0.6695)          (20.020)
nivel_tec_3                    0.0018            0.0358
                             (0.6243)          (13.331)
nivel_tec_4                    0.0024            0.0372
                             (0.9382)          (15.802)
nivel_tec_5                    0.0048            0.0389
                             (1.3193)          (11.068)
======================= ============= =================
Effects                        Entity
-------------------------------------------------------

T-stats reported in parentheses

### Instrumentalização da variável superior_med e minimos quadrados em dois estágios

In [11]:
from linearmodels.iv import IV2SLS
import statsmodels.formula.api as smf

# --- 1. Modelo IV (2SLS) ---
model_iv = IV2SLS.from_formula(
    'y_log ~ 1 + idade_med + idade_med_quadrado + sexo_med + raca_cor_med + '
    'nivel_tec_1 + nivel_tec_2 + nivel_tec_3 + nivel_tec_4 + nivel_tec_5 '
    '+ [superior_med ~ adultos_med]', 
    data=df
)
results_iv = model_iv.fit(cov_type='robust')
print(results_iv.summary)

# --- 2. Verificação do Instrumento ---
print("\n=== TESTE DE RELEVÂNCIA DO INSTRUMENTO ===")

# Rodar regressão

base = df[['y_log', 'adultos_med', 'idade_med', 'superior_med', 'idade_med_quadrado', 'sexo_med', 'raca_cor_med', 'sexo_raca_interacao', 'nivel_tec_1', 'nivel_tec_2', 'nivel_tec_3', 'nivel_tec_4', 'nivel_tec_5']].dropna()
X = base[['adultos_med', 'idade_med', 'superior_med', 'idade_med_quadrado', 'sexo_med', 'raca_cor_med', 'sexo_raca_interacao', 'nivel_tec_1', 'nivel_tec_2', 'nivel_tec_3', 'nivel_tec_4', 'nivel_tec_5']]
Y = base[['y_log']]

first_stage_manual = sm.OLS(Y, X).fit()

# Obter resultados
f_stat = first_stage_manual.fvalue
coef_instrumento = first_stage_manual.params['adultos_med']

print(f"\n=== RESULTADOS MANUAIS DO 1º ESTÁGIO ===")
print(f"Estatística F: {f_stat:.4f}")
print(f"Coeficiente do instrumento: {coef_instrumento:.4f}")
print(f"Valor-p do instrumento: {first_stage_manual.pvalues['adultos_med']:.4f}")

if f_stat > 10:
    print("✅ Instrumento forte (F > 10)")
else:
    print("⚠️ Atenção: Instrumento potencialmente fraco (F ≤ 10)")

# --- 3. Modelo MQO para Hausman (DEVE USAR smf.ols) ---
model_ols = smf.ols(
    'y_log ~ 1 + superior_med + idade_med + idade_med_quadrado + '
    'sexo_med + raca_cor_med + nivel_tec_1 + nivel_tec_2 + nivel_tec_3 + nivel_tec_4 + nivel_tec_5', 
    data=df
)
results_ols = model_ols.fit(cov_type='HC3')  # Erros robustos
print("\n--------------------------------------------")
print(results_ols.summary())

# --- 4. Teste de Hausman ---
hausman_test = results_iv.wu_hausman()
print("\n=== TESTE DE HAUSMAN ===")
print(f"Estatística: {hausman_test.stat:.4f}")
print(f"p-valor: {hausman_test.pval:.4f}")

if hausman_test.pval < 0.05:
    print("✅ Rejeita H0: 'superior_med' é endógena (use IV2SLS).")
else:
    print("✅ Não rejeita H0: 'superior_med' pode ser exógena (MQO é válido).")

/home/ph-padrim/Área de trabalho/Trabalho de Econometria/trabalho 2/novo_venv/lib/python3.12/site-packages/linearmodels/iv/model.py:557: MissingValueWarning:
Inputs contain missing values. Dropping rows with missing observations.
  super().__init__(

                          IV-2SLS Estimation Summary
==============================================================================
Dep. Variable:                  y_log   R-squared:                     -0.0542
Estimator:                    IV-2SLS   Adj. R-squared:                -0.0542
No. Observations:              311862   F-statistic:                 3.335e+04
Date:                Fri, Jun 27 2025   P-value (F-stat)                0.0000
Time:                        08:03:13   Distribution:                 chi2(10)
Cov. Estimator:                robust

                                 Parameter Estimates
======================================================================================
                    Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
--------------------------------------------------------------------------------------
Intercept              6.7588     0.0294     229.95     0.0000      6.7012      6.8164
idade_med              0.0262     0.0017     15.035     0.0000      0.0228      0.0296
idade_med_quadrado    -0.0003  2.214e-05    -12.986     0.0000     -0.0003     -0.0002
sexo_med              -0.3440     0.0079    -43.510     0.0000     -0.3595     -0.3285
raca_cor_med           0.0483     0.0042     11.641     0.0000      0.0402      0.0565
nivel_tec_1           -0.0337     0.0073    -4.5962     0.0000     -0.0481     -0.0193
nivel_tec_2           -0.0391     0.0075    -5.1952     0.0000     -0.0539     -0.0244
nivel_tec_3           -0.0356     0.0084    -4.2385     0.0000     -0.0521     -0.0192
nivel_tec_4           -0.0316     0.0080    -3.9406     0.0001     -0.0473     -0.0159
nivel_tec_5           -0.0330     0.0105    -3.1332     0.0017     -0.0536     -0.0124
superior_med           2.4751     0.1103     22.447     0.0000      2.2590      2.6912
======================================================================================

Endogenous: superior_med
Instruments: adultos_med
Robust Covariance (Heteroskedastic)
Debiased: False

=== TESTE DE RELEVÂNCIA DO INSTRUMENTO ===

=== RESULTADOS MANUAIS DO 1º ESTÁGIO ===
Estatística F: 6006868.7177
Coeficiente do instrumento: -0.9419
Valor-p do instrumento: 0.0000
✅ Instrumento forte (F > 10)

--------------------------------------------
                            OLS Regression Results
==============================================================================
Dep. Variable:                  y_log   R-squared:                       0.326
Model:                            OLS   Adj. R-squared:                  0.326
Method:                 Least Squares   F-statistic:                     7307.
Date:                Fri, 27 Jun 2025   Prob (F-statistic):               0.00
Time:                        08:03:15   Log-Likelihood:            -1.1891e+05
No. Observations:              311862   AIC:                         2.378e+05
Df Residuals:                  311851   BIC:                         2.380e+05
Df Model:                          10
Covariance Type:                  HC3
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept              6.4581      0.011    590.037      0.000       6.437       6.480
superior_med           1.0839      0.006    176.133      0.000       1.072       1.096
idade_med              0.0445      0.001     72.035      0.000       0.043       0.046
idade_med_quadrado    -0.0005   8.51e-06    -60.666      0.000      -0.001      -0.000
sexo_med              -0.2492      0.002   -142.788      0.000      -0.253      -0.246
raca_cor_med           0.0044      0.002      2.600      0.009       0.001       0.008
nivel_tec_1            0.0554      0.002     34.675      0.000       0.052       0.059
nivel_tec_2            0.0509      0.002     26.677      0.000       0.047       0.055
nivel_tec_3            0.0493      0.004     12.033      0.000       0.041       0.057
nivel_tec_4            0.0541      0.003     15.867      0.000       0.047       0.061
nivel_tec_5            0.0555      0.006      8.912      0.000       0.043       0.068
==============================================================================
Omnibus:                    33817.051   Durbin-Watson:                   0.821
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           284956.261
Skew:                           0.169   Prob(JB):                         0.00
Kurtosis:                       7.671   Cond. No.                     2.30e+04
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 2.3e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

=== TESTE DE HAUSMAN ===
Estatística: 361.2270
p-valor: 0.0000
✅ Rejeita H0: 'superior_med' é endógena (use IV2SLS).

#### DIFF IN DIFF

In [12]:
# --- Dividir o DataFrame 'df' em dois novos DataFrames ---

# DataFrame onde 'ano_classificado' é igual a 1
df_ano_1 = dados_limpos_index[dados_limpos_index['ano_classificado'] == 1].copy()

# DataFrame onde 'ano_classificado' é igual a 0
df_ano_0 = dados_limpos_index[dados_limpos_index['ano_classificado'] == 0].copy()

# ==============================================
# 1. MODELO POOLED OLS PARA O ANO 2021
# ==============================================
dados_limpos_index_exogenas = df_ano_1[['nivel_tec_classificado']]
exogenas_com_intercepto = sm.add_constant(dados_limpos_index_exogenas)
modelo_pooled = PooledOLS(dependent=df_ano_1['y_log'], exog=exogenas_com_intercepto).fit()
print(modelo_pooled.summary)

# ================================================
# 1. MODELO POOLED OLS PARA ANOS ANTERIORES A 2021
# ================================================
dados_limpos_index_exogenas = df_ano_0[['nivel_tec_classificado']]
exogenas_com_intercepto = sm.add_constant(dados_limpos_index_exogenas)
modelo_pooled = PooledOLS(dependent=df_ano_0['y_log'], exog=exogenas_com_intercepto).fit()
print(modelo_pooled.summary)

# ================================================
# 1. MODELO POOLED OLS CONSIDERANDO A INTERAÇÃO
# ================================================ 
dados_limpos_index_exogenas = dados_limpos_index[['tec_ano_interacao', 'ano_classificado', 'nivel_tec_classificado']]
exogenas_com_intercepto = sm.add_constant(dados_limpos_index_exogenas)

modelo_pooled = PooledOLS(dependent=dados_limpos_index['y_log'], exog=exogenas_com_intercepto).fit()
print(modelo_pooled.summary)

                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:                  y_log   R-squared:                     8.041e-05
Estimator:                  PooledOLS   R-squared (Between):           8.041e-05
No. Observations:               42031   R-squared (Within):               0.0000
Date:                Fri, Jun 27 2025   R-squared (Overall):           8.041e-05
Time:                        08:03:21   Log-likelihood                -2.604e+04
Cov. Estimator:            Unadjusted
                                        F-statistic:                      3.3799
Entities:                       42031   P-value                           0.0660
Avg Obs:                       1.0000   Distribution:                 F(1,42029)
Min Obs:                       1.0000
Max Obs:                       1.0000   F-statistic (robust):             3.3799
                                        P-value                           0.0660
Time periods:                       1   Distribution:                 F(1,42029)
Avg Obs:                    4.203e+04
Min Obs:                    4.203e+04
Max Obs:                    4.203e+04

                                   Parameter Estimates
==========================================================================================
                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------------------
const                      7.3280     0.0022     3320.4     0.0000      7.3236      7.3323
nivel_tec_classificado     0.0365     0.0198     1.8384     0.0660     -0.0024      0.0754
==========================================================================================
                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:                  y_log   R-squared:                        0.0006
Estimator:                  PooledOLS   R-squared (Between):              0.0009
No. Observations:              269831   R-squared (Within):              -0.0030
Date:                Fri, Jun 27 2025   R-squared (Overall):              0.0006
Time:                        08:03:22   Log-likelihood                 -1.54e+05
Cov. Estimator:            Unadjusted
                                        F-statistic:                      153.75
Entities:                       63050   P-value                           0.0000
Avg Obs:                       4.2796   Distribution:                F(1,269829)
Min Obs:                       1.0000
Max Obs:                       5.0000   F-statistic (robust):             153.75
                                        P-value                           0.0000
Time periods:                       5   Distribution:                F(1,269829)
Avg Obs:                    5.397e+04
Min Obs:                    4.672e+04
Max Obs:                     5.94e+04

                                   Parameter Estimates
==========================================================================================
                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------------------
const                      7.3655     0.0008     8878.0     0.0000      7.3638      7.3671
nivel_tec_classificado     0.0900     0.0073     12.400     0.0000      0.0758      0.1042
==========================================================================================
                          PooledOLS Estimation Summary
================================================================================
Dep. Variable:                  y_log   R-squared:                        0.0014
Estimator:                  PooledOLS   R-squared (Between):              0.0007
No. Observations:              311862   R-squared (Within):               0.0038
Date:                Fri, Jun 27 2025   R-squared (Overall):              0.0014
Time:                        08:03:22   Log-likelihood                -1.801e+05
Cov. Estimator:            Unadjusted
                                        F-statistic:                      147.06
Entities:                       63239   P-value                           0.0000
Avg Obs:                       4.9315   Distribution:                F(3,311858)
Min Obs:                       1.0000
Max Obs:                       6.0000   F-statistic (robust):             147.06
                                        P-value                           0.0000
Time periods:                       6   Distribution:                F(3,311858)
Avg Obs:                    5.198e+04
Min Obs:                    4.203e+04
Max Obs:                     5.94e+04

                                   Parameter Estimates
==========================================================================================
                        Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------------------
const                      7.3655     0.0008     8817.0     0.0000      7.3638      7.3671
tec_ano_interacao         -0.0535     0.0204    -2.6272     0.0086     -0.0935     -0.0136
ano_classificado          -0.0375     0.0023    -16.483     0.0000     -0.0420     -0.0330
nivel_tec_classificado     0.0900     0.0073     12.314     0.0000      0.0757      0.1043
==========================================================================================